spring:
  profiles:
    active: prod
---
spring:
 profiles: dev
 datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql:///spring712
    username: root
---
spring:
  profiles: prod
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: kalia
    type: org.apache.commons.dbcp.BasicDataSource
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
---
spring:
  profiles: test
  datasource:
    driver-class-name: org.postgresql.Driver
    password: kalia
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:postgresql:///spring712
    username: postgres
